# Update version number if needed
if(DEFINED BUILD_NUMBER)
  set(PROJECT_VERSION_TWEAK       ${BUILD_NUMBER})
  set(PROJECT_VERSION             ${PROJECT_VERSION_MAJOR}.${PROJECT_VERSION_MINOR}.${PROJECT_VERSION_PATCH}.${PROJECT_VERSION_TWEAK})
  set(CMAKE_PROJECT_VERSION_TWEAK ${BUILD_NUMBER})
  set(CMAKE_PROJECT_VERSION       ${CMAKE_PROJECT_VERSION_MAJOR}.${CMAKE_PROJECT_VERSION_MINOR}.${CMAKE_PROJECT_VERSION_PATCH}.${CMAKE_PROJECT_VERSION_TWEAK})
endif()
